version: '3'
services:
  pe1:
    # build: ../docker/grp
    build: ../docker/frr
    cap_add:
      - NET_ADMIN
    privileged: true
    tty: true
    volumes:
      - ../../:/go/grp
      - ./pe1/:/tmp/pe1
    networks:
      link0:
        ipv4_address: 10.0.0.2
      link1:
        ipv4_address: 10.0.1.3
  pe2:
    build: ../docker/frr
    cap_add:
      - NET_ADMIN
    privileged: true
    tty: true
    volumes:
      - ./pe2/data:/tmp/data
    networks:
      link0:
        ipv4_address: 10.0.0.3
      link2:
        ipv4_address: 10.0.2.4
networks:
  link0:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.0.0/24
  link1:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
  link2:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 10.0.2.0/24
